JAVAFLAGS = -g 

all: hw1

clean:
	rm -f *.class

# hw1: PlayGame.java DeckOfCards.java BaseCard.java Card.java JokerCard.java Player.java
# 	javac $(JAVAFLAGS) PlayGame.java DeckOfCards.java BaseCard.java Card.java JokerCard.java Player.java

hw1 : *.java
	javac $(JAVAFLAGS) *java